# docker-compose.yml
version: '2'

services:
  service-discovery:
    image: cloudbot/service-discovery
    ports:
      - "8100:8100"
  
  config-server:
    image: cloudbot/config-server


  docker-api:
    image: cloudbot/docker-api
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    
  rabbitmq:
    image: rabbitmq:3.7.8-alpine

  bot-manager:
    image: cloudbot/bot-manager
    ports:
      - "8101:8101"
    depends_on:
      - service-discovery
      - config-server
      - neo4j
      - rabbitmq
      - docker-api
  
  service-manager:
    image: cloudbot/service-manager
    ports:
      - "8102:8102"
    depends_on:
      - rabbitmq
      - service-manager-redis


  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none

  gateway:
    image: cloudbot/gateway
    ports:
      - "8120:8120"
    depends_on:
      - service-manager
      - bot-manager
  
  service-manager-redis:
    image: redis:5.0-alpine


networks:
  default:
    external:
      name: cloud-bot-network
